#!/usr/bin/env bash
# configures a ufw firewall to block all incoming traffic
# except for TCP ports 22, 443, and 80.

# Checks the path of ufw which is pre-installed
which ufw

# Checks the status of the ufw which should be inactive on default
sudo ufw status

sudo apt-get install -y ufw
sudo ufw disable
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw enable

# verify the rules added to ufw
sudo ufw status
